name: dart_dsa
description: Data structure and algorithms using Dart
version: 1.0.0
repository: https://github.com/techoshik/dart-data-structure-and-algorithms

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
